// تعريف إعدادات الموقع (المجموعات والحقول والقيم الافتراضية)
// كل حقل يظهر تلقائيًا في لوحة التحكم ← الإعدادات / التسويق / SEO

export const SETTINGS_GROUPS = [
  {
    key: 'general',
    title: 'هوية الموقع والتواصل',
    icon: 'building',
    permission: 'settings',
    fields: [
      { name: 'site_name', label: 'اسم الشركة', type: 'text', default: 'شركة إصغاء للمحاماة والاستشارات القانونية' },
      { name: 'brand_short', label: 'الاسم المختصر', type: 'text', default: 'إصغاء' },
      { name: 'site_tagline', label: 'الشعار النصي', type: 'text', default: 'محامون • مستشارون • محكمون • موثقون' },
      { name: 'site_description', label: 'نبذة قصيرة (تظهر في الفوتر)', type: 'textarea', default: 'شركة مهنية مؤسسة وفق أنظمة المملكة العربية السعودية، تقدم خدمات قانونية متميزة.' },
      { name: 'logo', label: 'الشعار (خلفية فاتحة)', type: 'image', default: '/img/logo.svg' },
      { name: 'logo_compact', label: 'الشعار المختصر للقائمة', type: 'image', default: '/img/logo-compact-white.svg', hint: 'يظهر داخل شريط القائمة الداكن — يفضّل نسخة بيضاء.' },
      { name: 'logo_white', label: 'الشعار (خلفية داكنة)', type: 'image', default: '/img/logo-white.svg' },
      { name: 'phone', label: 'رقم الهاتف', type: 'text', default: '0558882700', dir: 'ltr' },
      { name: 'whatsapp', label: 'رقم واتساب (دولي بدون +)', type: 'text', default: '966558882700', dir: 'ltr' },
      { name: 'whatsapp_message', label: 'رسالة واتساب الافتراضية', type: 'text', default: 'السلام عليكم، أرغب في استشارة قانونية.' },
      { name: 'email', label: 'البريد الإلكتروني', type: 'text', default: 'info@isgha.sa', dir: 'ltr' },
      { name: 'address', label: 'العنوان الكامل', type: 'textarea', default: 'المملكة العربية السعودية – الرياض – حي الياسمين – طريق أبي بكر الصديق – مقابل مقر شركة ثمانية' },
      { name: 'address_short', label: 'العنوان المختصر', type: 'text', default: 'الرياض — حي الياسمين' },
      { name: 'city', label: 'المدينة', type: 'text', default: 'الرياض' },
      { name: 'working_hours', label: 'ساعات العمل', type: 'text', default: 'الأحد – الخميس · ٩ صباحًا – ٥ مساءً' },
      { name: 'map_query', label: 'موقع الخريطة (عنوان أو إحداثيات)', type: 'text', default: 'طريق أبي بكر الصديق، حي الياسمين، الرياض', hint: 'يُستخدم لعرض خريطة جوجل في صفحة التواصل. يمكن كتابة إحداثيات مثل 24.8241,46.6402' },
      { name: 'map_link', label: 'رابط الموقع على خرائط جوجل', type: 'text', default: '', dir: 'ltr' },
      { name: 'license_note', label: 'نص الترخيص', type: 'text', default: 'مرخّصة من الهيئة السعودية للمحامين' },
      { name: 'social_x', label: 'حساب X', type: 'text', default: '', dir: 'ltr' },
      { name: 'social_linkedin', label: 'لينكدإن', type: 'text', default: '', dir: 'ltr' },
      { name: 'social_instagram', label: 'إنستغرام', type: 'text', default: '', dir: 'ltr' },
      { name: 'social_snapchat', label: 'سناب شات', type: 'text', default: '', dir: 'ltr' },
      { name: 'social_tiktok', label: 'تيك توك', type: 'text', default: '', dir: 'ltr' },
      { name: 'social_youtube', label: 'يوتيوب', type: 'text', default: '', dir: 'ltr' },
    ],
  },
  {
    key: 'navigation',
    title: 'القائمة والفوتر',
    icon: 'menu',
    permission: 'settings',
    fields: [
      {
        name: 'nav_items', label: 'عناصر القائمة الرئيسية', type: 'repeater', itemLabel: 'label',
        fields: [
          { name: 'label', label: 'النص', type: 'text' },
          { name: 'url', label: 'الرابط', type: 'text', dir: 'ltr' },
          { name: 'dropdown', label: 'قائمة منسدلة', type: 'select', options: [['', 'بدون'], ['services', 'الخدمات تلقائيًا']] },
        ],
        default: [
          { label: 'الرئيسية', url: '/', dropdown: '' },
          { label: 'من نحن', url: '/about', dropdown: '' },
          { label: 'خدماتنا', url: '/services', dropdown: 'services' },
          { label: 'المستفيدون', url: '/beneficiaries', dropdown: '' },
          { label: 'المعرفة القانونية', url: '/insights', dropdown: '' },
          { label: 'اتصل بنا', url: '/contact', dropdown: '' },
        ],
      },
      { name: 'nav_cta_label', label: 'زر القائمة', type: 'text', default: 'احجز استشارة' },
      { name: 'nav_cta_url', label: 'رابط زر القائمة', type: 'text', default: '/consultation', dir: 'ltr' },
      { name: 'mega_note', label: 'نص أسفل قائمة الخدمات المنسدلة', type: 'text', default: 'غير متأكد من الخدمة المناسبة؟' },
      { name: 'mega_cta_label', label: 'رابط أسفل قائمة الخدمات — النص', type: 'text', default: 'اطلب تقييمًا أوليًا' },
      { name: 'mega_cta_url', label: 'رابط أسفل قائمة الخدمات — الرابط', type: 'text', default: '/consultation', dir: 'ltr' },
      { name: 'footer_heading', label: 'عنوان الفوتر', type: 'text', default: 'خطوتك الأولى نحو حقك تبدأ من هنا' },
      { name: 'footer_cta_label', label: 'زر الفوتر', type: 'text', default: 'احجز استشارتك' },
      { name: 'footer_cta_url', label: 'رابط زر الفوتر', type: 'text', default: '/consultation', dir: 'ltr' },
      { name: 'footer_services_title', label: 'الفوتر — عنوان عمود الخدمات', type: 'text', default: 'خدماتنا', hint: 'أقسام الخدمات تظهر تحته تلقائيًا، ثم الروابط الإضافية التالية.' },
      { name: 'footer_services_links', label: 'الفوتر — روابط إضافية في عمود الخدمات', type: 'list', default: [], hint: 'سطر لكل رابط بالشكل: النص | الرابط' },
      { name: 'footer_links_title', label: 'الفوتر — عنوان عمود الروابط', type: 'text', default: 'روابط سريعة' },
      { name: 'footer_links', label: 'الفوتر — الروابط السريعة', type: 'list', default: ['من نحن | /about', 'المستفيدون | /beneficiaries', 'المعرفة القانونية | /insights', 'طلب استشارة | /consultation', 'اتصل بنا | /contact'], hint: 'سطر لكل رابط بالشكل: النص | الرابط' },
      { name: 'footer_contact_title', label: 'الفوتر — عنوان عمود التواصل', type: 'text', default: 'تواصل معنا' },
      { name: 'footer_legal_links', label: 'الفوتر — الروابط القانونية أسفل الصفحة', type: 'list', default: ['سياسة الخصوصية | /privacy-policy', 'شروط الاستخدام | /terms', 'خريطة الموقع | /sitemap.xml'], hint: 'سطر لكل رابط بالشكل: النص | الرابط' },
      { name: 'mega_word', label: 'الكلمة الضخمة أسفل الصفحة', type: 'text', default: 'إصْغَـــاء' },
      { name: 'copyright', label: 'نص الحقوق', type: 'text', default: '© {year} شركة إصغاء للمحاماة والاستشارات القانونية. جميع الحقوق محفوظة.', hint: '{year} تُستبدل بالسنة الحالية تلقائيًا.' },
      { name: 'show_whatsapp_float', label: 'زر واتساب العائم', type: 'toggle', default: true },
      { name: 'show_mobile_callbar', label: 'شريط الاتصال في الجوال', type: 'toggle', default: true },
    ],
  },
  {
    key: 'texts',
    title: 'نصوص الموقع',
    icon: 'type',
    permission: 'settings',
    fields: [
      { name: 'txt_call_now', label: 'زر الاتصال', type: 'text', default: 'اتصل الآن' },
      { name: 'txt_whatsapp', label: 'زر واتساب', type: 'text', default: 'واتساب' },
      { name: 'txt_whatsapp_float', label: 'تلميح زر واتساب العائم', type: 'text', default: 'تواصل عبر واتساب' },
      { name: 'txt_wa_inquiry', label: 'بداية رسالة واتساب عند الاستفسار عن خدمة', type: 'text', default: 'السلام عليكم، أستفسر عن ' },
      { name: 'txt_book', label: 'زر حجز الاستشارة', type: 'text', default: 'احجز استشارة' },
      { name: 'txt_cookie_ok', label: 'زر الموافقة على ملفات الارتباط', type: 'text', default: 'موافق' },
      { name: 'txt_cat_areas_title', label: 'صفحة قسم الخدمات — عنوان الخدمات التفصيلية', type: 'text', default: 'مجالات الخدمة بالتفصيل' },
      { name: 'txt_cat_specs_title', label: 'صفحة قسم الخدمات — عنوان مجالات التخصص', type: 'text', default: 'مجالات تخصصنا' },
      { name: 'txt_cat_practice_title', label: 'صفحة الخدمات القضائية — عنوان مجالات العمل', type: 'text', default: 'مجالات العمل القضائي' },
      { name: 'txt_cat_cta_title', label: 'صفحة قسم الخدمات — عنوان الدعوة', type: 'text', default: 'هل تحتاج رأيًا قانونيًا الآن؟' },
      { name: 'txt_cat_cta_text', label: 'صفحة قسم الخدمات — نص الدعوة', type: 'textarea', default: 'تواصل مع محامٍ مختص يوضح لك موقفك وخياراتك قبل أي التزام.' },
      { name: 'txt_assess', label: 'زر طلب التقييم الأولي', type: 'text', default: 'اطلب تقييمًا أوليًا' },
      { name: 'txt_svc_includes', label: 'صفحة الخدمة — عنوان البنود الافتراضي', type: 'text', default: 'تشمل الخدمة' },
      { name: 'txt_svc_cta_title', label: 'صفحة الخدمة — عنوان الدعوة', type: 'text', default: 'ناقش {service} مع محامٍ مختص', hint: '{service} تُستبدل باسم الخدمة.' },
      { name: 'txt_svc_cta_text', label: 'صفحة الخدمة — نص الدعوة', type: 'textarea', default: 'نستمع لتفاصيلك ونوضح لك الخيارات والتكلفة بوضوح قبل أي التزام.' },
      { name: 'txt_svc_direct', label: 'صفحة الخدمة — عنوان التواصل المباشر', type: 'text', default: 'تواصل مباشرة' },
      { name: 'txt_post_toc', label: 'المقال — عنوان المحتويات', type: 'text', default: 'محتويات المقال' },
      { name: 'txt_post_share', label: 'المقال — مشاركة', type: 'text', default: 'شارك المقال:' },
      { name: 'txt_post_disclaimer', label: 'المقال — تنبيه قانوني', type: 'textarea', default: 'تنبيه: المحتوى للتوعية العامة ولا يُعد استشارة قانونية لحالتك. للحصول على رأي قانوني دقيق تواصل مع محامٍ مختص.' },
      { name: 'txt_post_cta_title', label: 'المقال — عنوان الدعوة', type: 'text', default: 'لديك حالة مشابهة؟' },
      { name: 'txt_post_cta_text', label: 'المقال — نص الدعوة', type: 'textarea', default: 'احصل على تقييم أولي من محامٍ مختص خلال ساعات العمل.' },
      { name: 'txt_post_related', label: 'المقال — مقالات ذات صلة', type: 'text', default: 'مقالات ذات صلة' },
      { name: 'txt_read_post', label: 'زر قراءة المقال', type: 'text', default: 'اقرأ المقال' },
      { name: 'txt_blog_all', label: 'المدونة — تبويب الكل', type: 'text', default: 'الكل' },
      { name: 'txt_blog_empty', label: 'المدونة — عند عدم وجود مقالات', type: 'text', default: 'قريبًا: مقالات وإرشادات قانونية يكتبها فريق إصغاء.' },
      { name: 'txt_thanks_tag', label: 'صفحة الشكر — الوسم', type: 'text', default: 'تم استلام طلبك' },
      { name: 'txt_back_home', label: 'زر العودة للرئيسية', type: 'text', default: 'العودة للرئيسية' },
      { name: 'txt_404_title', label: 'صفحة غير موجودة — العنوان', type: 'text', default: 'الصفحة التي تبحث عنها غير موجودة' },
      { name: 'txt_404_text', label: 'صفحة غير موجودة — النص', type: 'textarea', default: 'ربما تغيّر الرابط أو حُذفت الصفحة. يمكنك العودة للرئيسية أو التواصل معنا مباشرة.' },
      { name: 'txt_404_links', label: 'صفحة غير موجودة — الأزرار', type: 'list', default: ['الصفحة الرئيسية | /', 'خدماتنا | /services', 'اتصل بنا | /contact'], hint: 'سطر لكل رابط بالشكل: النص | الرابط' },
    ],
  },
  {
    key: 'leads',
    title: 'النماذج والعملاء',
    icon: 'inbox',
    permission: 'settings',
    fields: [
      { name: 'case_types', label: 'أنواع القضايا في نموذج التقييم', type: 'list', default: ['تجاري وشركات', 'عمالي', 'أحوال شخصية', 'عقاري', 'تنفيذ أحكام', 'أخرى'] },
      { name: 'contact_services', label: 'خيارات «نوع الخدمة» في نموذج التواصل', type: 'list', default: ['الخدمات القضائية', 'الخدمات القانونية', 'خدمات التوثيق العدلي', 'الخدمات المتخصصة', 'الباقات القانونية للشركات'] },
      { name: 'notify_emails', label: 'إرسال إشعار كل طلب جديد إلى', type: 'text', default: 'info@isgha.sa', dir: 'ltr', hint: 'أكثر من بريد؟ افصل بينها بفاصلة.' },
      { name: 'webhook_url', label: 'Webhook لإرسال العملاء (CRM / Google Sheets / n8n)', type: 'text', default: '', dir: 'ltr' },
      { name: 'webhook_secret', label: 'مفتاح سري للـ Webhook (اختياري)', type: 'secret', default: '' },
      { name: 'thank_you_mode', label: 'بعد إرسال النموذج', type: 'select', options: [['inline', 'رسالة شكر في نفس الصفحة'], ['redirect', 'تحويل لصفحة الشكر /thank-you']], default: 'redirect', hint: 'التحويل لصفحة الشكر يسهّل تتبع التحويلات في إعلانات جوجل وسناب.' },
    ],
  },
  {
    key: 'smtp',
    title: 'البريد الصادر (SMTP)',
    icon: 'mail',
    permission: 'settings',
    fields: [
      { name: 'smtp_host', label: 'خادم SMTP', type: 'text', default: 'smtp.hostinger.com', dir: 'ltr' },
      { name: 'smtp_port', label: 'المنفذ', type: 'text', default: '465', dir: 'ltr' },
      { name: 'smtp_secure', label: 'اتصال آمن SSL', type: 'toggle', default: true },
      { name: 'smtp_user', label: 'اسم المستخدم', type: 'text', default: '', dir: 'ltr' },
      { name: 'smtp_pass', label: 'كلمة المرور', type: 'secret', default: '' },
      { name: 'smtp_from', label: 'المرسل', type: 'text', default: '', dir: 'ltr', hint: 'مثال: إصغاء <no-reply@isgha.sa>' },
    ],
  },
  {
    key: 'marketing',
    title: 'الإعلانات والتتبع',
    icon: 'megaphone',
    permission: 'marketing',
    fields: [
      { name: 'gtm_id', label: 'Google Tag Manager', type: 'text', default: '', dir: 'ltr', placeholder: 'GTM-XXXXXXX' },
      { name: 'ga4_id', label: 'Google Analytics 4', type: 'text', default: '', dir: 'ltr', placeholder: 'G-XXXXXXXXXX' },
      { name: 'google_ads_id', label: 'Google Ads — Conversion ID', type: 'text', default: '', dir: 'ltr', placeholder: 'AW-123456789' },
      { name: 'google_ads_lead_label', label: 'Google Ads — Label تحويل الطلب', type: 'text', default: '', dir: 'ltr' },
      { name: 'google_ads_call_label', label: 'Google Ads — Label نقرة الاتصال', type: 'text', default: '', dir: 'ltr' },
      { name: 'meta_pixel_id', label: 'Meta (Facebook/Instagram) Pixel', type: 'text', default: '', dir: 'ltr' },
      { name: 'meta_capi_token', label: 'Meta Conversions API — Access Token', type: 'secret', default: '', hint: 'يرسل حدث Lead من السيرفر مباشرة (يتجاوز مانعات الإعلانات ويحسّن المطابقة).' },
      { name: 'meta_test_code', label: 'Meta — Test Event Code', type: 'text', default: '', dir: 'ltr', hint: 'للاختبار فقط، احذفه بعد التأكد.' },
      { name: 'tiktok_pixel_id', label: 'TikTok Pixel', type: 'text', default: '', dir: 'ltr' },
      { name: 'snap_pixel_id', label: 'Snapchat Pixel', type: 'text', default: '', dir: 'ltr' },
      { name: 'x_pixel_id', label: 'X (Twitter) Pixel', type: 'text', default: '', dir: 'ltr' },
      { name: 'x_lead_event', label: 'X — Event ID للطلب', type: 'text', default: '', dir: 'ltr', placeholder: 'tw-xxxxx-xxxxx' },
      { name: 'linkedin_partner_id', label: 'LinkedIn Insight — Partner ID', type: 'text', default: '', dir: 'ltr' },
      { name: 'linkedin_conversion_id', label: 'LinkedIn — Conversion ID', type: 'text', default: '', dir: 'ltr' },
      { name: 'clarity_id', label: 'Microsoft Clarity', type: 'text', default: '', dir: 'ltr' },
      { name: 'head_code', label: 'كود إضافي داخل <head>', type: 'code', default: '' },
      { name: 'body_start_code', label: 'كود بعد <body>', type: 'code', default: '' },
      { name: 'body_end_code', label: 'كود قبل </body>', type: 'code', default: '' },
    ],
  },
  {
    key: 'seo',
    title: 'محركات البحث',
    icon: 'search',
    permission: 'seo',
    fields: [
      { name: 'seo_title_suffix', label: 'لاحقة عناوين الصفحات', type: 'text', default: ' | إصغاء للمحاماة والاستشارات القانونية' },
      { name: 'seo_default_title', label: 'عنوان الصفحة الرئيسية', type: 'text', default: 'إصغاء للمحاماة والاستشارات القانونية — محامون في الرياض', hint: 'يفضّل ألا يتجاوز 60 حرفًا حتى يظهر كاملًا في جوجل.' },
      { name: 'seo_default_description', label: 'الوصف الافتراضي', type: 'textarea', default: 'شركة إصغاء للمحاماة والاستشارات القانونية — محامون، مستشارون، محكمون، موثقون. تمثيل قضائي، استشارات، تأسيس شركات، توثيق عدلي وباقات قانونية للشركات في المملكة العربية السعودية.' },
      { name: 'seo_og_image', label: 'صورة المشاركة الافتراضية', type: 'image', default: '/img/og-default.jpg' },
      { name: 'seo_keywords', label: 'كلمات مفتاحية', type: 'text', default: 'محامي الرياض، مكتب محاماة، استشارات قانونية، تأسيس شركات، توثيق عدلي، محامي تجاري، محامي عمالي، تحكيم' },
      { name: 'canonical_host', label: 'الدومين الأساسي (Canonical)', type: 'text', default: '', dir: 'ltr', hint: 'مثال: https://isgha.sa — يُستخدم في الروابط القانونية وخريطة الموقع. اتركه فارغًا لاستخدام الدومين الحالي.' },
      { name: 'google_verification', label: 'Google Search Console — رمز التحقق', type: 'text', default: '', dir: 'ltr' },
      { name: 'bing_verification', label: 'Bing Webmaster — رمز التحقق', type: 'text', default: '', dir: 'ltr' },
      { name: 'yandex_verification', label: 'Yandex — رمز التحقق', type: 'text', default: '', dir: 'ltr' },
      { name: 'facebook_verification', label: 'Facebook Domain Verification', type: 'text', default: '', dir: 'ltr' },
      { name: 'robots_extra', label: 'قواعد robots.txt إضافية', type: 'code', default: '' },
      { name: 'org_legal_name', label: 'الاسم النظامي', type: 'text', default: 'شركة إصغاء للمحاماة والاستشارات القانونية' },
      { name: 'org_founding_year', label: 'سنة التأسيس', type: 'text', default: '' },
      { name: 'org_geo', label: 'الإحداثيات (lat,lng)', type: 'text', default: '', dir: 'ltr' },
      { name: 'org_areas', label: 'المناطق المخدومة', type: 'text', default: 'الرياض، جدة، مكة المكرمة، المدينة المنورة، أبها' },
    ],
  },
  {
    key: 'privacy',
    title: 'الخصوصية',
    icon: 'shield',
    permission: 'settings',
    fields: [
      { name: 'cookie_notice', label: 'إظهار تنبيه ملفات الارتباط', type: 'toggle', default: false },
      { name: 'cookie_text', label: 'نص التنبيه', type: 'textarea', default: 'نستخدم ملفات الارتباط لتحسين تجربتك وقياس أداء الإعلانات. باستمرارك في التصفح فأنت توافق على سياسة الخصوصية.' },
    ],
  },
];

export const SECRET_KEYS = SETTINGS_GROUPS.flatMap((g) => g.fields.filter((f) => f.type === 'secret').map((f) => f.name));

export function settingDefaults() {
  const out = {};
  for (const g of SETTINGS_GROUPS) for (const f of g.fields) out[f.name] = f.default ?? '';
  return out;
}
